package installer
package main

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

//go:embed prompts/*.md
var promptFiles embed.FS

//go:embed agents/*.md
var agentFiles embed.FS

// Version is set via ldflags during build: -X main.Version=$(VERSION)
var Version = "0.1.0"

func main() {









































































































































































}	}		fmt.Println("No extension files found to remove")	} else {		fmt.Println("Extensions uninstalled successfully!")		fmt.Printf("✓ Removed %d extension files\n", removedCount)	if removedCount > 0 {	}		}			removedCount++		if err := os.Remove(path); err == nil {		path := filepath.Join(agentsDir, file)	for _, file := range agentFiles {	// Remove agents	}		}			removedCount++		if err := os.Remove(path); err == nil {		path := filepath.Join(promptsDir, file)	for _, file := range promptFiles {	// Remove prompts	removedCount := 0	}		"smaqit.user-testing.agent.md",		"smaqit.release.agent.md",	agentFiles := []string{	}		"test.start.prompt.md",		"task.complete.prompt.md",		"task.list.prompt.md",		"task.create.prompt.md",		"session.title.prompt.md",		"session.finish.prompt.md",		"session.assess.prompt.md",		"session.start.prompt.md",	promptFiles := []string{	// List files to remove	agentsDir := filepath.Join(targetDir, ".github", "agents")	promptsDir := filepath.Join(targetDir, ".github", "prompts")	targetDir := "."func cmdUninstall() {}	fmt.Println("  Use agents: @smaqit.release, @smaqit.user-testing")	fmt.Println("  Use prompts in GitHub Copilot: /session.start, /task.create, etc.")	fmt.Println("Get started:")	fmt.Println()	fmt.Println("Extensions installed successfully!")	fmt.Println()	fmt.Printf("✓ Installed %d agents to %s\n", agentCount, agentsDir)	fmt.Printf("✓ Installed %d prompts to %s\n", promptCount, promptsDir)	}		os.Exit(1)		fmt.Printf("Error installing agents: %v\n", err)	}); err != nil {		return nil		agentCount++		}			return fmt.Errorf("writing %s: %w", targetPath, err)		if err := os.WriteFile(targetPath, content, 0644); err != nil {		targetPath := filepath.Join(agentsDir, filename)		filename := filepath.Base(path)		}			return fmt.Errorf("reading %s: %w", path, err)		if err != nil {		content, err := fs.ReadFile(agentFiles, path)		}			return nil		if d.IsDir() {		}			return err		if err != nil {	if err := fs.WalkDir(agentFiles, "agents", func(path string, d fs.DirEntry, err error) error {	agentCount := 0	// Install agents	}		os.Exit(1)		fmt.Printf("Error installing prompts: %v\n", err)	}); err != nil {		return nil		promptCount++		}			return fmt.Errorf("writing %s: %w", targetPath, err)		if err := os.WriteFile(targetPath, content, 0644); err != nil {		targetPath := filepath.Join(promptsDir, filename)		filename := filepath.Base(path)		}			return fmt.Errorf("reading %s: %w", path, err)		if err != nil {		content, err := fs.ReadFile(promptFiles, path)		}			return nil		if d.IsDir() {		}			return err		if err != nil {	if err := fs.WalkDir(promptFiles, "prompts", func(path string, d fs.DirEntry, err error) error {	promptCount := 0	// Install prompts	}		os.Exit(1)		fmt.Printf("Error creating agents directory: %v\n", err)	if err := os.MkdirAll(agentsDir, 0755); err != nil {	}		os.Exit(1)		fmt.Printf("Error creating prompts directory: %v\n", err)	if err := os.MkdirAll(promptsDir, 0755); err != nil {	agentsDir := filepath.Join(targetDir, ".github", "agents")	promptsDir := filepath.Join(targetDir, ".github", "prompts")	// Create target directoriesfunc cmdInstall(targetDir string) {}	fmt.Println("  .github/agents/     - 2 utility agents")	fmt.Println("  .github/prompts/    - 8 workflow prompts")	fmt.Println("What gets installed:")	fmt.Println()	fmt.Println("  smaqit-extensions uninstall Remove extensions from current directory")	fmt.Println("  smaqit-extensions --version Show version")	fmt.Println("  smaqit-extensions --help   Show this help message")	fmt.Println("  smaqit-extensions <dir>    Install extensions in specified directory")	fmt.Println("  smaqit-extensions          Install extensions in current directory")	fmt.Println("Commands:")	fmt.Println()	fmt.Println("Usage: smaqit-extensions [dir]")	fmt.Printf("Version: %s\n\n", Version)	fmt.Println("smaqit-extensions - Quality-of-life extensions for smaqit")func printHelp() {}	cmdInstall(targetDir)	}		targetDir = os.Args[1]	if len(os.Args) > 1 {	targetDir := "."	// Default: install extensions	}		}			return			cmdUninstall()		case "uninstall":			return			printHelp()		case "help", "--help", "-h":			return			fmt.Printf("smaqit-extensions %s\n", Version)		case "version", "--version", "-v":		switch os.Args[1] {	if len(os.Args) > 1 {